version: "3.7"
services:

    tiff_downloader:
        build: 
            context: .
            dockerfile: Dockerfile
        image: tiff_downloader
        container_name: tiff_downloader
        restart: unless-stopped
        environment: 
            - READ_DOT_ENV=True
        ports:
            - 8000:8000
        volumes:
            - /home/dev/ttif:/app/pyramid_tiff
        networks: 
            - tiff_downloader

networks: 
    tiff_downloader:
        name: tiff_downloader
